# Generated by Django 5.1.2 on 2025-09-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
