# Generated by Django 5.1.2 on 2025-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en el local'), ('delivery', 'Delivery')], default='retiro', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
