# Generated by Django 5.1.2 on 2025-10-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_metodo_entrega_order_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('en_preparacion', 'En Preparación'), ('listo', 'Listo para Entregar'), ('en_camino', 'En Camino'), ('enviado', 'Enviado / Entregado'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=20),
        ),
    ]
