# Generated by Django 5.1.2 on 2025-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercadopago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
    ]
